// Mocks generated by Mockito 5.4.5 from annotations
// in aura_app/test/features/ecommerce/presentation/screens/product_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aura_app/features/ecommerce/domain/entities/product.dart'
    as _i6;
import 'package:aura_app/features/ecommerce/presentation/notifiers/product_detail_notifier.dart'
    as _i3;
import 'package:aura_app/features/ecommerce/presentation/notifiers/product_detail_state.dart'
    as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDetailState_0 extends _i1.SmartFake
    implements _i2.ProductDetailState {
  _FakeProductDetailState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDetailNotifier extends _i1.Mock
    implements _i3.ProductDetailNotifier {
  MockProductDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.ProductDetailState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.ProductDetailState>.empty(),
      ) as _i5.Stream<_i2.ProductDetailState>);

  @override
  _i2.ProductDetailState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductDetailState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.ProductDetailState);

  @override
  set state(_i2.ProductDetailState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ProductDetailState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeProductDetailState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.ProductDetailState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #loadProduct,
          [productId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setProduct(_i6.Product? product) => super.noSuchMethod(
        Invocation.method(
          #setProduct,
          [product],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectImage(int? index) => super.noSuchMethod(
        Invocation.method(
          #selectImage,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateQuantity(int? newQuantity) => super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [newQuantity],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void incrementQuantity() => super.noSuchMethod(
        Invocation.method(
          #incrementQuantity,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void decrementQuantity() => super.noSuchMethod(
        Invocation.method(
          #decrementQuantity,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectVariant(
    String? variantType,
    String? variantValue,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #selectVariant,
          [
            variantType,
            variantValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFavorite() => super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> addToCart() => (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateShouldNotify(
    _i2.ProductDetailState? old,
    _i2.ProductDetailState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.RemoveListener addListener(
    _i7.Listener<_i2.ProductDetailState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
