name: aura_app
description: "AI-powered Personal Style Assistant - Aura Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Functional Programming
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Networking
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  image: ^4.1.7
  
  # Security
  flutter_secure_storage: ^9.2.2
  
  # UI/UX
  lottie: ^3.1.2
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  
  # Navigation
  go_router: ^14.2.7
  
  # Utilities
  json_annotation: ^4.9.0
  uuid: ^4.3.3
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4

dev_dependencies:
  # Code Generation
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  hive_generator: 2.0.1
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  
  # Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1
  
  # Linting and Code Quality
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/animations/

  # Note: Using Google Fonts for Montserrat family
  # No need for local font files
