// Mocks generated by Mockito 5.4.5 from annotations
// in aura_app/test/features/ecommerce/domain/usecases/search_products_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aura_app/core/error/failures.dart' as _i5;
import 'package:aura_app/features/ecommerce/domain/entities/product.dart'
    as _i6;
import 'package:aura_app/features/ecommerce/domain/repositories/ecommerce_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EcommerceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcommerceRepository extends _i1.Mock
    implements _i3.EcommerceRepository {
  MockEcommerceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>> searchProducts({
    required String? query,
    _i6.ProductFilter? filters,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #filters: filters,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProductSearchResult>(
          this,
          Invocation.method(
            #searchProducts,
            [],
            {
              #query: query,
              #filters: filters,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Product?>> getProductById(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [productId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Product?>>.value(
            _FakeEither_0<_i5.Failure, _i6.Product?>(
          this,
          Invocation.method(
            #getProductById,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Product?>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.ProductSearchResult>> getTrendingProducts({
    String? category,
    String? timePeriod = 'week',
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendingProducts,
          [],
          {
            #category: category,
            #timePeriod: timePeriod,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProductSearchResult>(
          this,
          Invocation.method(
            #getTrendingProducts,
            [],
            {
              #category: category,
              #timePeriod: timePeriod,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>
      getProductRecommendations({
    String? productId,
    String? category,
    List<String>? tags,
    int? limit = 10,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getProductRecommendations,
              [],
              {
                #productId: productId,
                #category: category,
                #tags: tags,
                #limit: limit,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.Product>>(
              this,
              Invocation.method(
                #getProductRecommendations,
                [],
                {
                  #productId: productId,
                  #category: category,
                  #tags: tags,
                  #limit: limit,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i6.ProductSearchResult>> getProductsByCategory({
    required String? category,
    _i6.ProductFilter? filters,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [],
          {
            #category: category,
            #filters: filters,
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>.value(
                _FakeEither_0<_i5.Failure, _i6.ProductSearchResult>(
          this,
          Invocation.method(
            #getProductsByCategory,
            [],
            {
              #category: category,
              #filters: filters,
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ProductSearchResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getBrands(
          {String? category}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBrands,
          [],
          {#category: category},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getBrands,
            [],
            {#category: category},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}
